name: Build Kivy APK 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-17-jdk python3-setuptools
          pip install buildozer cython

      - name: Install buildozer requirements
        run: |
          sudo apt install -y libncurses5-dev libstdc++6 libffi-dev libssl-dev \
                              zlib1g zlib1g-dev libjpeg-dev

      - name: Build APK
        run: |
          sudo apt install -y git
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-app-apk
          path: bin/*.apk
